# Master database, write operations
master.jdbc.url=jdbc:mysql://127.0.0.1:3306/=utf-8
master.jdbc.username=root
master.jdbc.password=root
master.jdbc.driver=com.mysql.jdbc.Driver

# Read database, read operations
read.jdbc.url=jdbc:mysql://127.0.0.1:3306/=utf-8
read.jdbc.username=root
read.jdbc.password=root
read.jdbc.driver=com.mysql.jdbc.Driver
